- webvtt.go
There is a logic bug in skipping the webvtt header:
``line != "WEBVTT"`` should really be ``line == "WEBVTT"``
This worked previously because the header line had UTF-8 byte order mark characters in it.
This PR strips the BOM char before comparison and also fixes the header detection logic.
Edited to add:
Without this fix, processing ascii webvtt files will erroneously drop the first subtitle line.
> Strip BOM from line when skipping header (webvtt)

- ttml.go
- ttml_internal_test.go
while parsing TTML, i noticed that you only support clock time format, and no offset format
see: https://www.w3.org/TR/ttaf1-dfxp/#timing-value-timeExpression
this is a "first draft" implementation
> implement offset time

- subtitles.go
I encountered upper case filenames and it was more appropriate to fix the extension dispatcher rather than renaming files, as there is no need to enforce lower case filenames.
> add support in Open() for upper case extensions

- srt.go
- webvtt.go
Hi! I'm by no means an expert of WebVTT format but this fixed a parsing problem for me. Feel free to reject if it's a bad change, or improve it or whatever you'd like.
PS. It'd be really helpful to output the line number when an error is encountered. Would you be open to a PR for that?
> webvtt,srt: Tolerate edge whitespace (and print line numbers on error)

- testdata/broken-in.vtt
- webvtt.go
- webvtt_test.go
Adds a simple test file, `broken-in.vtt`, that starts with a single space character, followed by a newline. In master this file panics with an index out-of-bounds error. This is fixed by checking both that the line length is greater than zero, and that the resulting fields length is also greater than zero.
I've also added a very, very simple test case that can be used to confirm that the current behavior is broken in master.
> Fix a bug parsing lines with only spaces

- ttml.go
- ttml_internal_test.go
I tested it with some examples and it should work. For instance, you can take the example Netflix subtitles:
```
<?xml version="1.0" encoding="UTF-8"?>
<tt xmlns="http://www.w3.org/ns/ttml" xmlns:tt="http://www.w3.org/ns/ttml" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling" ttp:tickRate="10000000" ttp:version="2" xml:lang="ja">
<head>
<styling>
<initial tts:backgroundColor="transparent" tts:color="white" tts:fontSize="6.000vh"/>
<style xml:id="style0" tts:textAlign="center"/>
<style xml:id="style1" tts:textAlign="start"/>
<style xml:id="style2" tts:ruby="container" tts:rubyPosition="auto"/>
<style xml:id="style3" tts:ruby="base"/>
<style xml:id="style4" tts:ruby="text"/>
<style xml:id="style5" …
```
> Implement tick duration support for TTML subtitles

- webvtt.go
Does the job when converting STL to WebVTT.
I think the webVTTBytes() code could probably be further refactored, to ensure it would support both font style and color, for example, but I wanted to keep this PR minimal.
At first, it could set a local variable for color, booleans for italics and other style, depending on the various settings in InlineStyle (eg. italics could come from WebVTTItalics, but also from TTMLFontStyle). Then for every variable set, print the starting vtt code, then print the text, then for every variable set, print the ending vtt code.
BTW, I didn't find a place where WebVTTItalics is set ...
> webvtt: add colored output

- subtitles.go
WebVTT output will have the align:left or align:right if the corresponding STL justification was set in input.
> support stl justification when converting to webvtt

- srt.go
Today, my colleague and I encountered a panic and found that an error occurred while translating the file, and the error was located in srt.go. After investigation, there was an error in a certain line of the file, but it was not printed in srt.go.For example,our srt file format has a timeline and corresponding subtitles, but if there are multiple lines of subtitles, it will panic. Under normal circumstances, it should be an error and return an error and then print the log, not panic.Therefore, we hope to add a line of code to print the number of wrong lines in srt.go to facilitate the location of errors.
> Print out the wrong number of lines when an error occurs

- stl.go
- subtitles.go
When reading STL files, astisub subtracts the value of timecodeStartOfProgramme from all Item timecodes. In our project we need to know if this has happend, and what this value was.
> Add STLTimecodeStartOfProgramme to Metadata

- stl.go
- subtitles.go
Solves #49 using an option parameter in STLOptions similar to what is available for Teletext.
> Add STL option to ignore start of programme timecode

- stl.go
Fixes bad vertical positioning (less than 1 or greater than 23) on closed subtitles when writing STL. Replaces https://github.com/asticode/go-astisub/pull/39
> stl: validate vertical position for closed subtitles

- ssa.go
Originated from https://github.com/asticode/go-astisub/issues/59
> Solved https://github.com/asticode/go-astisub/issues/59

- webvtt.go
- webvtt_internal_test.go
- webvtt_test.go
When specified, X-TIMESTAMP-MAP should be used to compute an offset for
each subtitle record in the file.
> webvtt: Handle X-TIMESTAMP-MAP header

- subtitles.go
It should work with both teletext (Max Number of Rows = 23) and in-vision (MNR=0..99) subtitles, but only tested on teletext subtitles (no-op if MNR == 0 to avoid zero division).
It propagates the STL VP to the WebVTT line attribute, as percentage, by diving the row number by the max number of rows.
For example, if VP = 22 in a teletext TTI, then percentage = int(22*100/23) = 95, thus it will output "line:95%" in the VTT file.
> Propagate STL vertical position to WebVTT

- subtitles.go
Would you believe I made an off-by-one error when converting the STL vertical position of a teletext subtitle (going from 1 to 23) to a WebVTT line percentage (starting from 0% -- a line at the bottom should be at about 91%) ?
It appeared correctly in VLC and iOS native player, but in some other players (Shaka ...), the vertical positioning was visibly too low.
This PR fixes the problem by subtracting 1 to the row number when converting a teletext subtitle.
> fix vertical position conversion from stl teletext to webvtt

- webvtt.go
- webvtt_test.go
Hi all,
We have already escape "&" because of my reporting in this ticket https://github.com/asticode/go-astisub/issues/85, but we are lacking of escape-unescape for "<", with escape-unescape "<" character, we can fulfill the requirement of WebVTT format in escaping characters.
> escape-unescape '<' character for WebVTT

- subtitles.go
- testdata/example-in.vtt
- testdata/example-out.vtt
- webvtt.go
Hi all,
Now, we will lose all of WebVTT style after reading it, process somethings and write to WebVTT format again. This PR provide a simple WebVTT style handling, since CSS support many properties, I will not parsing them all, we will just blindly store all the things in `STYLE` and rewrite them when writing WebVTT again. We will love some spaces and new lines, but it's not a big duel. Besides, when merging `subtitles2` into `subtitles1`, if there are duplicated CSS selectors, only the CSS style of `subtitles1` will be kept.
> Simple support for WebVTT style

- subtitles.go
- webvtt.go
- webvtt_internal_test.go
- webvtt_test.go
Hi all,
WebVTT STYLE block is CSS and it allow to write custom CSS class or tag in xml to applied to the lines of WebVTT, also, some default tag like tag i (italic), b (bold), u (underline), etc are supported too, for example:
```
WEBVTT
00:01:00.000 --> 00:02:00.000
<u><i>Italic with underline text</i></u> some extra
00:02:00.000 --> 00:03:00.000
<lang en>English here</lang> <c.yellow.bg_blue>Yellow text on blue background</c>
00:03:00.000 --> 00:04:00.000
<v Joe><c.red><i>Joe's words are red in italic</i></c>
00:04:00.000 --> 00:05:00.000
<customed_tag.class1.class2>Text here</customed_tag>
```
So, I add these change to preserve the tags in WebVTT files. This will be convenient if someday, we decide to convert styling from WebVTT to TTML or another format.
According to WebVTT format at: …
> Preserve WebVTT tags in subtitle lines

- subtitles.go
- webvtt.go
- webvtt_internal_test.go
- webvtt_test.go
> Add support for inline timestamps

- testdata/example-in-breaklines.ttml
- testdata/example-out-breaklines.ttml
- ttml.go
Hi,
My apologize, after changing the token reader to decoder, the code does not work as expected. Or we can say that the polymorphism of Golang is not like what we have in C++, Java, etc, there is no parent and child object so I miss-understood that it will work as expected. I need to wash my brain after years of coding in traditional polymophism. And, with some coincidence, I let vscode extension to automatically edit the input ttml, that extension added some more newlines character and make the output is pretty normal to me and I am blind. My carelessness :bow:
> [ttml] Rename ttml decoder to token reader and correct test data

- subtitles.go
- webvtt.go
- webvtt_internal_test.go
- webvtt_test.go
As I mentioned in [this issue here](https://github.com/asticode/go-astisub/issues/111), I'd like to be able to specify an `X-TIMESTAMP-MAP` based on some external factors in my application which uses astisub. However, as part of this, I think that the WebVTT reader automatically applying the time offset defined therein will cause duplicate applications of the time offset in the case where a WebVTT with an `X-TIMESTAMP-MAP` is read, manipulated, then also written back out. 
So this PR adds a struct for storing the parsed `X-TIMESTAMP-MAP` data on the `Subtitles`' Metadata field, that way it can be manually applied to the subtitles if necessary, or left as is and written back to WebVTT files so that some upstream client can apply the time correction. Likewise, this also allows manually …
> fix: Add support for X-TIMESTAMP-MAP r/w persistence

- srt.go
- srt_test.go
- webvtt.go
- webvtt_test.go
This PR allows for somewhat more lenient parsing of the timestamps for srt and vtt. For both srt and vtt this allows for timestamps to use the separator without the surrounding spaces. For example:
```
00:00:01.876-->00:0:03.390
```
For vtt, this PR also allows for parsing timestamps where the inline styles are separated by tabs `\t`.
> Allow for more lenient duration parsing

- srt.go
- srt_test.go
- subtitles_internal_test.go
This PR allows for the `:` delimiter when parsing milliseconds on srt files.
> Add support for colon delimited milliseconds for srt
